export const mockUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-15'),
};

export const mockItemTypes = [
  { id: 'type_1', name: 'snippet',  icon: 'Code',       color: '#3b82f6', isSystem: true },
  { id: 'type_2', name: 'prompt',   icon: 'Sparkles',   color: '#8b5cf6', isSystem: true },
  { id: 'type_3', name: 'command',  icon: 'Terminal',   color: '#f97316', isSystem: true },
  { id: 'type_4', name: 'note',     icon: 'StickyNote', color: '#fde047', isSystem: true },
  { id: 'type_5', name: 'file',     icon: 'File',       color: '#6b7280', isSystem: true },
  { id: 'type_6', name: 'image',    icon: 'Image',      color: '#ec4899', isSystem: true },
  { id: 'type_7', name: 'link',     icon: 'Link',       color: '#10b981', isSystem: true },
];

export const mockCollections = [
  {
    id: 'coll_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    isPinned: true,
    hasFavoriteItem: true,
    itemCount: 12,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',     color: '#3b82f6', count: 8 },
      { typeId: 'type_3', icon: 'Terminal', color: '#f97316', count: 3 },
      { typeId: 'type_7', icon: 'Link',     color: '#10b981', count: 1 },
    ],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coll_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 8,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code', color: '#3b82f6', count: 6 },
      { typeId: 'type_7', icon: 'Link', color: '#10b981', count: 2 },
    ],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'coll_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 5,
    typeDistribution: [
      { typeId: 'type_5', icon: 'File',  color: '#6b7280', count: 3 },
      { typeId: 'type_6', icon: 'Image', color: '#ec4899', count: 2 },
    ],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'coll_4',
    name: 'Interview Prep',
    description: 'Resources for interview preparation',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: true,
    itemCount: 34,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',     color: '#3b82f6', count: 15 },
      { typeId: 'type_2', icon: 'Sparkles', color: '#8b5cf6', count: 12 },
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 7 },
    ],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'coll_5',
    name: 'Git Commands',
    description: 'Commonly used git commands',
    isFavorite: true,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 7,
    typeDistribution: [
      { typeId: 'type_3', icon: 'Terminal', color: '#f97316', count: 7 },
    ],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'coll_6',
    name: 'AI Prompts',
    description: 'Curated prompts for coding',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 6,
    typeDistribution: [
      { typeId: 'type_2', icon: 'Sparkles', color: '#8b5cf6', count: 4 },
      { typeId: 'type_7', icon: 'Link',     color: '#10b981', count: 2 },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coll_7',
    name: 'TypeScript Utils',
    description: 'Reusable TypeScript utility types and helpers',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 9,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',       color: '#3b82f6', count: 7 },
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 2 },
    ],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: 'coll_8',
    name: 'DevOps Toolkit',
    description: 'Docker, CI/CD, and deployment scripts',
    isFavorite: true,
    isPinned: true,
    hasFavoriteItem: true,
    itemCount: 14,
    typeDistribution: [
      { typeId: 'type_3', icon: 'Terminal', color: '#f97316', count: 9 },
      { typeId: 'type_1', icon: 'Code',     color: '#3b82f6', count: 3 },
      { typeId: 'type_7', icon: 'Link',     color: '#10b981', count: 2 },
    ],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'coll_9',
    name: 'Design Resources',
    description: 'UI inspiration, color palettes, and design tools',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 11,
    typeDistribution: [
      { typeId: 'type_7', icon: 'Link',  color: '#10b981', count: 8 },
      { typeId: 'type_6', icon: 'Image', color: '#ec4899', count: 3 },
    ],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: 'coll_10',
    name: 'SQL Queries',
    description: 'Frequently used SQL patterns and optimizations',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 7,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',       color: '#3b82f6', count: 5 },
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 2 },
    ],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'coll_11',
    name: 'Next.js Patterns',
    description: 'App router patterns, server actions, and data fetching',
    isFavorite: true,
    isPinned: false,
    hasFavoriteItem: true,
    itemCount: 16,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',       color: '#3b82f6', count: 10 },
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 4 },
      { typeId: 'type_7', icon: 'Link',       color: '#10b981', count: 2 },
    ],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: 'coll_12',
    name: 'Regex Cookbook',
    description: 'Handy regular expressions for common parsing tasks',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 10,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',       color: '#3b82f6', count: 8 },
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 2 },
    ],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'coll_13',
    name: 'Security Notes',
    description: 'OWASP checklists, auth flows, and security best practices',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 8,
    typeDistribution: [
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 5 },
      { typeId: 'type_7', icon: 'Link',       color: '#10b981', count: 3 },
    ],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'coll_14',
    name: 'Node.js Scripts',
    description: 'Automation and utility scripts for backend tasks',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 13,
    typeDistribution: [
      { typeId: 'type_1', icon: 'Code',     color: '#3b82f6', count: 8 },
      { typeId: 'type_3', icon: 'Terminal', color: '#f97316', count: 5 },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'coll_15',
    name: 'API References',
    description: 'Links to REST, GraphQL, and SDK documentation',
    isFavorite: false,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 5,
    typeDistribution: [
      { typeId: 'type_7', icon: 'Link', color: '#10b981', count: 5 },
    ],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'coll_16',
    name: 'VS Code Setup',
    description: 'Extensions, settings, and keybindings for VS Code',
    isFavorite: true,
    isPinned: false,
    hasFavoriteItem: false,
    itemCount: 6,
    typeDistribution: [
      { typeId: 'type_4', icon: 'StickyNote', color: '#fde047', count: 3 },
      { typeId: 'type_3', icon: 'Terminal',   color: '#f97316', count: 2 },
      { typeId: 'type_7', icon: 'Link',       color: '#10b981', count: 1 },
    ],
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-26'),
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT' as const,
    content: 'const useAuth = () => {\n  // Custom auth hook implementation\n}',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Custom authentication hook for React applications',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_react', name: 'react' }, { id: 'tag_auth', name: 'auth' }, { id: 'tag_hooks', name: 'hooks' }],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'TEXT' as const,
    content: 'try {\n  // API call\n} catch (error) {\n  // Handle error\n}',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_api', name: 'api' }, { id: 'tag_error-handling', name: 'error-handling' }],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'item_3',
    title: 'Code Review Prompt',
    contentType: 'TEXT' as const,
    content: 'Review this code for security and performance issues...',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Prompt for AI code reviews',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    itemType: { id: 'type_2', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
    tags: [{ id: 'tag_ai', name: 'ai' }, { id: 'tag_code-review', name: 'code-review' }],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'item_4',
    title: 'git reset --hard HEAD~1',
    contentType: 'TEXT' as const,
    content: 'git reset --hard HEAD~1',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Reset to previous commit (destructive)',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_git', name: 'git' }, { id: 'tag_reset', name: 'reset' }],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'item_5',
    title: 'useLocalStorage Hook',
    contentType: 'TEXT' as const,
    content: 'const useLocalStorage = (key, initialValue) => { ... }',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Persistent state management with localStorage',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_react', name: 'react' }, { id: 'tag_hooks', name: 'hooks' }, { id: 'tag_storage', name: 'storage' }],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'item_6',
    title: 'Docker Compose Up',
    contentType: 'TEXT' as const,
    content: 'docker-compose up -d --build',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Start containers in detached mode with rebuild',
    isFavorite: true,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_docker', name: 'docker' }, { id: 'tag_devops', name: 'devops' }],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'item_7',
    title: 'Explain Code Prompt',
    contentType: 'TEXT' as const,
    content: 'Explain this code step by step, highlighting key concepts...',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'AI prompt for code explanations',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    itemType: { id: 'type_2', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
    tags: [{ id: 'tag_ai', name: 'ai' }, { id: 'tag_learning', name: 'learning' }],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'item_8',
    title: 'Meeting Notes Template',
    contentType: 'TEXT' as const,
    content: '# Meeting Notes\n\n## Date:\n## Attendees:\n## Agenda:\n## Action Items:',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Markdown template for meeting notes',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    itemTypeId: 'type_4',
    itemType: { id: 'type_4', name: 'note', icon: 'StickyNote', color: '#fde047', isSystem: true },
    tags: [{ id: 'tag_template', name: 'template' }, { id: 'tag_meetings', name: 'meetings' }],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'item_9',
    title: 'Prisma Migration Command',
    contentType: 'TEXT' as const,
    content: 'npx prisma migrate dev --name migration_name',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Create and apply Prisma database migration',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_prisma', name: 'prisma' }, { id: 'tag_database', name: 'database' }],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'item_10',
    title: 'React Query Setup',
    contentType: 'TEXT' as const,
    content: 'const queryClient = new QueryClient()',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'TanStack Query client configuration',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_react', name: 'react' }, { id: 'tag_data-fetching', name: 'data-fetching' }],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'item_11',
    title: 'GitHub Actions Workflow',
    contentType: 'TEXT' as const,
    content: 'name: CI\non: [push, pull_request]',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Basic CI/CD workflow template',
    isFavorite: false,
    isPinned: false,
    language: 'yaml',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_ci-cd', name: 'ci-cd' }, { id: 'tag_github', name: 'github' }],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'item_12',
    title: 'Tailwind CSS Resources',
    contentType: 'URL' as const,
    content: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: 'https://tailwindcss.com/docs',
    description: 'Official Tailwind CSS documentation',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_7',
    itemType: { id: 'type_7', name: 'link', icon: 'Link', color: '#10b981', isSystem: true },
    tags: [{ id: 'tag_css', name: 'css' }, { id: 'tag_docs', name: 'docs' }],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: 'item_13',
    title: 'Debounce Hook',
    contentType: 'TEXT' as const,
    content: 'const useDebounce = <T>(value: T, delay: number): T => { ... }',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Delays updating a value until after a specified wait period',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_react', name: 'react' }, { id: 'tag_hooks', name: 'hooks' }, { id: 'tag_performance', name: 'performance' }],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'item_14',
    title: 'Docker Prune All',
    contentType: 'TEXT' as const,
    content: 'docker system prune -a --volumes',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Remove all unused containers, images, networks and volumes',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_docker', name: 'docker' }, { id: 'tag_cleanup', name: 'cleanup' }],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'item_15',
    title: 'System Prompt Template',
    contentType: 'TEXT' as const,
    content: 'You are an expert software engineer. Your task is to...',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Base system prompt for coding assistants',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    itemType: { id: 'type_2', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
    tags: [{ id: 'tag_ai', name: 'ai' }, { id: 'tag_system-prompt', name: 'system-prompt' }],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: 'item_16',
    title: 'Zod Schema Validation',
    contentType: 'TEXT' as const,
    content: 'const schema = z.object({ email: z.string().email() })',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Runtime type validation with Zod for form inputs',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_validation', name: 'validation' }, { id: 'tag_zod', name: 'zod' }, { id: 'tag_typescript', name: 'typescript' }],
    createdAt: new Date('2023-12-31'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'item_17',
    title: 'Project Architecture Notes',
    contentType: 'TEXT' as const,
    content: '# Architecture\n\n## Frontend\n- Next.js App Router\n\n## Backend\n- Prisma + Neon',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'High-level architecture decisions for the project',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    itemTypeId: 'type_4',
    itemType: { id: 'type_4', name: 'note', icon: 'StickyNote', color: '#fde047', isSystem: true },
    tags: [{ id: 'tag_architecture', name: 'architecture' }, { id: 'tag_notes', name: 'notes' }],
    createdAt: new Date('2023-12-30'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'item_18',
    title: 'Kill Port Process',
    contentType: 'TEXT' as const,
    content: 'lsof -ti:3000 | xargs kill -9',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Force kill whatever process is running on a given port',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_terminal', name: 'terminal' }, { id: 'tag_ports', name: 'ports' }],
    createdAt: new Date('2023-12-29'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'item_19',
    title: 'Prisma Documentation',
    contentType: 'URL' as const,
    content: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: 'https://www.prisma.io/docs',
    description: 'Official Prisma ORM documentation',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_7',
    itemType: { id: 'type_7', name: 'link', icon: 'Link', color: '#10b981', isSystem: true },
    tags: [{ id: 'tag_prisma', name: 'prisma' }, { id: 'tag_docs', name: 'docs' }, { id: 'tag_database', name: 'database' }],
    createdAt: new Date('2023-12-28'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'item_20',
    title: 'useFetch Hook',
    contentType: 'TEXT' as const,
    content: 'const useFetch = <T>(url: string) => { const [data, setData] = useState<T | null>(null); ... }',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Generic data fetching hook with loading and error states',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    itemType: { id: 'type_1', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
    tags: [{ id: 'tag_react', name: 'react' }, { id: 'tag_hooks', name: 'hooks' }, { id: 'tag_fetch', name: 'fetch' }],
    createdAt: new Date('2023-12-27'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: 'item_21',
    title: 'Refactor Prompt',
    contentType: 'TEXT' as const,
    content: 'Refactor the following code to improve readability and performance without changing its behavior...',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'AI prompt for clean code refactoring',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    itemType: { id: 'type_2', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
    tags: [{ id: 'tag_ai', name: 'ai' }, { id: 'tag_refactor', name: 'refactor' }],
    createdAt: new Date('2023-12-26'),
    updatedAt: new Date('2024-01-27'),
  },
  {
    id: 'item_22',
    title: 'npm Audit Fix',
    contentType: 'TEXT' as const,
    content: 'npm audit fix --force',
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: 'Fix vulnerabilities in npm dependencies',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    itemType: { id: 'type_3', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
    tags: [{ id: 'tag_npm', name: 'npm' }, { id: 'tag_security', name: 'security' }],
    createdAt: new Date('2023-12-25'),
    updatedAt: new Date('2024-01-28'),
  },
];

export const mockItemTypeCounts = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 3,
  link: 8,
};
