export const mockUser = {
  id: 'user_1',
  email: 'demo@devstash.io',
  name: 'John Doe',
  isPro: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-15'),
};

export const mockItemTypes = [
  {
    id: 'type_1',
    name: 'snippet',
    icon: 'Code',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'type_2',
    name: 'prompt',
    icon: 'Sparkles',
    color: '#8b5cf6',
    isSystem: true,
  },
  {
    id: 'type_3',
    name: 'command',
    icon: 'Terminal',
    color: '#f97316',
    isSystem: true,
  },
  {
    id: 'type_4',
    name: 'note',
    icon: 'StickyNote',
    color: '#fde047',
    isSystem: true,
  },
  {
    id: 'type_5',
    name: 'file',
    icon: 'File',
    color: '#6b7280',
    isSystem: true,
  },
  {
    id: 'type_6',
    name: 'image',
    icon: 'Image',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'type_7',
    name: 'link',
    icon: 'Link',
    color: '#10b981',
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: 'coll_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    isPinned: true,
    itemCount: 12,
    typeDistribution: [
      { typeId: 'type_1', count: 8 },
      { typeId: 'type_3', count: 3 },
      { typeId: 'type_7', count: 1 },
    ],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coll_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    itemCount: 8,
    typeDistribution: [
      { typeId: 'type_1', count: 6 },
      { typeId: 'type_7', count: 2 },
    ],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'coll_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    itemCount: 5,
    typeDistribution: [
      { typeId: 'type_5', count: 3 },
      { typeId: 'type_6', count: 2 },
    ],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'coll_4',
    name: 'Interview Prep',
    description: 'Resources for interview preparation',
    isFavorite: false,
    itemCount: 34,
    typeDistribution: [
      { typeId: 'type_1', count: 15 },
      { typeId: 'type_2', count: 12 },
      { typeId: 'type_4', count: 7 },
    ],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'coll_5',
    name: 'Git Commands',
    description: 'Commonly used git commands',
    isFavorite: true,
    itemCount: 7,
    typeDistribution: [
      { typeId: 'type_3', count: 7 },
    ],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'coll_6',
    name: 'AI Prompts',
    description: 'Curated prompts for coding',
    isFavorite: false,
    itemCount: 6,
    typeDistribution: [
      { typeId: 'type_2', count: 4 },
      { typeId: 'type_7', count: 2 },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coll_7',
    name: 'TypeScript Utils',
    description: 'Reusable TypeScript utility types and helpers',
    isFavorite: false,
    isPinned: false,
    itemCount: 9,
    typeDistribution: [
      { typeId: 'type_1', count: 7 },
      { typeId: 'type_4', count: 2 },
    ],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: 'coll_8',
    name: 'DevOps Toolkit',
    description: 'Docker, CI/CD, and deployment scripts',
    isFavorite: true,
    isPinned: false,
    itemCount: 14,
    typeDistribution: [
      { typeId: 'type_3', count: 9 },
      { typeId: 'type_1', count: 3 },
      { typeId: 'type_7', count: 2 },
    ],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'coll_9',
    name: 'Design Resources',
    description: 'UI inspiration, color palettes, and design tools',
    isFavorite: false,
    isPinned: false,
    itemCount: 11,
    typeDistribution: [
      { typeId: 'type_7', count: 8 },
      { typeId: 'type_6', count: 3 },
    ],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: 'coll_10',
    name: 'SQL Queries',
    description: 'Frequently used SQL patterns and optimizations',
    isFavorite: false,
    isPinned: false,
    itemCount: 7,
    typeDistribution: [
      { typeId: 'type_1', count: 5 },
      { typeId: 'type_4', count: 2 },
    ],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'coll_11',
    name: 'Next.js Patterns',
    description: 'App router patterns, server actions, and data fetching',
    isFavorite: true,
    isPinned: false,
    itemCount: 16,
    typeDistribution: [
      { typeId: 'type_1', count: 10 },
      { typeId: 'type_4', count: 4 },
      { typeId: 'type_7', count: 2 },
    ],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: 'coll_12',
    name: 'Regex Cookbook',
    description: 'Handy regular expressions for common parsing tasks',
    isFavorite: false,
    isPinned: false,
    itemCount: 10,
    typeDistribution: [
      { typeId: 'type_1', count: 8 },
      { typeId: 'type_4', count: 2 },
    ],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'coll_13',
    name: 'Security Notes',
    description: 'OWASP checklists, auth flows, and security best practices',
    isFavorite: false,
    isPinned: false,
    itemCount: 8,
    typeDistribution: [
      { typeId: 'type_4', count: 5 },
      { typeId: 'type_7', count: 3 },
    ],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'coll_14',
    name: 'Node.js Scripts',
    description: 'Automation and utility scripts for backend tasks',
    isFavorite: false,
    isPinned: false,
    itemCount: 13,
    typeDistribution: [
      { typeId: 'type_1', count: 8 },
      { typeId: 'type_3', count: 5 },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'coll_15',
    name: 'API References',
    description: 'Links to REST, GraphQL, and SDK documentation',
    isFavorite: false,
    isPinned: false,
    itemCount: 5,
    typeDistribution: [
      { typeId: 'type_7', count: 5 },
    ],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'coll_16',
    name: 'VS Code Setup',
    description: 'Extensions, settings, and keybindings for VS Code',
    isFavorite: true,
    isPinned: false,
    itemCount: 6,
    typeDistribution: [
      { typeId: 'type_4', count: 3 },
      { typeId: 'type_3', count: 2 },
      { typeId: 'type_7', count: 1 },
    ],
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-26'),
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT',
    content: 'const useAuth = () => {\n  // Custom auth hook implementation\n}',
    description: 'Custom authentication hook for React applications',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'auth', 'hooks'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'TEXT',
    content: 'try {\n  // API call\n} catch (error) {\n  // Handle error\n}',
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['api', 'error-handling'],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: 'item_3',
    title: 'Code Review Prompt',
    contentType: 'TEXT',
    content: 'Review this code for security and performance issues...',
    description: 'Prompt for AI code reviews',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'code-review'],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: 'item_4',
    title: 'git reset --hard HEAD~1',
    contentType: 'TEXT',
    content: 'git reset --hard HEAD~1',
    description: 'Reset to previous commit (destructive)',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['git', 'reset'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'item_5',
    title: 'useLocalStorage Hook',
    contentType: 'TEXT',
    content: 'const useLocalStorage = (key, initialValue) => { ... }',
    description: 'Persistent state management with localStorage',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'hooks', 'storage'],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: 'item_6',
    title: 'Docker Compose Up',
    contentType: 'TEXT',
    content: 'docker-compose up -d --build',
    description: 'Start containers in detached mode with rebuild',
    isFavorite: true,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['docker', 'devops'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'item_7',
    title: 'Explain Code Prompt',
    contentType: 'TEXT',
    content: 'Explain this code step by step, highlighting key concepts...',
    description: 'AI prompt for code explanations',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'learning'],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'item_8',
    title: 'Meeting Notes Template',
    contentType: 'TEXT',
    content: '# Meeting Notes\n\n## Date:\n## Attendees:\n## Agenda:\n## Action Items:',
    description: 'Markdown template for meeting notes',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    itemTypeId: 'type_4',
    tags: ['template', 'meetings'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'item_9',
    title: 'Prisma Migration Command',
    contentType: 'TEXT',
    content: 'npx prisma migrate dev --name migration_name',
    description: 'Create and apply Prisma database migration',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['prisma', 'database'],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'item_10',
    title: 'React Query Setup',
    contentType: 'TEXT',
    content: 'const queryClient = new QueryClient()',
    description: 'TanStack Query client configuration',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'data-fetching'],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'item_11',
    title: 'GitHub Actions Workflow',
    contentType: 'TEXT',
    content: 'name: CI\non: [push, pull_request]',
    description: 'Basic CI/CD workflow template',
    isFavorite: false,
    isPinned: false,
    language: 'yaml',
    itemTypeId: 'type_1',
    tags: ['ci-cd', 'github'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'item_12',
    title: 'Tailwind CSS Resources',
    contentType: 'URL',
    content: null,
    url: 'https://tailwindcss.com/docs',
    description: 'Official Tailwind CSS documentation',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_7',
    tags: ['css', 'docs'],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: 'item_13',
    title: 'Debounce Hook',
    contentType: 'TEXT',
    content: 'const useDebounce = <T>(value: T, delay: number): T => { ... }',
    description: 'Delays updating a value until after a specified wait period',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'hooks', 'performance'],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'item_14',
    title: 'Docker Prune All',
    contentType: 'TEXT',
    content: 'docker system prune -a --volumes',
    description: 'Remove all unused containers, images, networks and volumes',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['docker', 'cleanup'],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'item_15',
    title: 'System Prompt Template',
    contentType: 'TEXT',
    content: 'You are an expert software engineer. Your task is to...',
    description: 'Base system prompt for coding assistants',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'system-prompt'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: 'item_16',
    title: 'Zod Schema Validation',
    contentType: 'TEXT',
    content: 'const schema = z.object({ email: z.string().email() })',
    description: 'Runtime type validation with Zod for form inputs',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['validation', 'zod', 'typescript'],
    createdAt: new Date('2023-12-31'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'item_17',
    title: 'Project Architecture Notes',
    contentType: 'TEXT',
    content: '# Architecture\n\n## Frontend\n- Next.js App Router\n\n## Backend\n- Prisma + Neon',
    description: 'High-level architecture decisions for the project',
    isFavorite: false,
    isPinned: false,
    language: 'markdown',
    itemTypeId: 'type_4',
    tags: ['architecture', 'notes'],
    createdAt: new Date('2023-12-30'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'item_18',
    title: 'Kill Port Process',
    contentType: 'TEXT',
    content: 'lsof -ti:3000 | xargs kill -9',
    description: 'Force kill whatever process is running on a given port',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['terminal', 'ports'],
    createdAt: new Date('2023-12-29'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'item_19',
    title: 'Prisma Documentation',
    contentType: 'URL',
    content: null,
    url: 'https://www.prisma.io/docs',
    description: 'Official Prisma ORM documentation',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_7',
    tags: ['prisma', 'docs', 'database'],
    createdAt: new Date('2023-12-28'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'item_20',
    title: 'useFetch Hook',
    contentType: 'TEXT',
    content: 'const useFetch = <T>(url: string) => { const [data, setData] = useState<T | null>(null); ... }',
    description: 'Generic data fetching hook with loading and error states',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_1',
    tags: ['react', 'hooks', 'fetch'],
    createdAt: new Date('2023-12-27'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: 'item_21',
    title: 'Refactor Prompt',
    contentType: 'TEXT',
    content: 'Refactor the following code to improve readability and performance without changing its behavior...',
    description: 'AI prompt for clean code refactoring',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_2',
    tags: ['ai', 'refactor'],
    createdAt: new Date('2023-12-26'),
    updatedAt: new Date('2024-01-27'),
  },
  {
    id: 'item_22',
    title: 'npm Audit Fix',
    contentType: 'TEXT',
    content: 'npm audit fix --force',
    description: 'Fix vulnerabilities in npm dependencies',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_3',
    tags: ['npm', 'security'],
    createdAt: new Date('2023-12-25'),
    updatedAt: new Date('2024-01-28'),
  },
];

export const mockItemTypeCounts = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 3,
  link: 8,
};
